name: trac_ik lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  trac_ik-lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8,
          lint_cmake, mypy, pep257, pep8, uncrustify, xmllint]
        package: [trac_ik_lib, trac_ik_examples]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: rolling

      - name: Lint trac_ik
        uses: ros-tooling/action-ros-lint@master
        with:
          package-name: ${{ matrix.package }}
          linter: ${{ matrix.linter }}

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: colcon_logs
          path: ${{ steps.action_ros_ci.outputs.ros-workspace-directory-name }}/log
        if: always()
