name: trac_ik lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, lint_cmake, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.2
        with:
          use-ros2-testing: true
          required-ros-distributions: rolling

      - name: Lint trac_ik
        uses: ros-tooling/action-ros-lint@master
        with:
          package-name: trac_ik
          linter: ${{ matrix.linter }}

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: colcon_logs
          path: ${{ steps.action_ros_ci.outputs.ros-workspace-directory-name }}/log
        if: always()
